controller_joint_names: ['', 'CoxisD_Joint', 'MusloD3_Joint', 'MusloD5_Joint', 'PantorrillaD_Joint', 'PieD9_Joint', 'PieD11_Joint', 'CoxisI_Joint', 'MusloI4_Joint', 'MusloI6_Joint', 'PantorrillaI_Joint', 'PieI10_Joint', 'PieI12_Joint', ]
