# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  CoxisD_Joint:
    has_velocity_limits: true
    max_velocity: 52
    has_acceleration_limits: false
    max_acceleration: 0
  CoxisI_Joint:
    has_velocity_limits: true
    max_velocity: 52
    has_acceleration_limits: false
    max_acceleration: 0
  MusloD3_Joint:
    has_velocity_limits: true
    max_velocity: 48
    has_acceleration_limits: false
    max_acceleration: 0
  MusloD5_Joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  MusloI4_Joint:
    has_velocity_limits: true
    max_velocity: 48
    has_acceleration_limits: false
    max_acceleration: 0
  MusloI6_Joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  PantorrillaD_Joint:
    has_velocity_limits: true
    max_velocity: 52
    has_acceleration_limits: false
    max_acceleration: 0
  PantorrillaI_Joint:
    has_velocity_limits: true
    max_velocity: 52
    has_acceleration_limits: false
    max_acceleration: 0
  PieD11_Joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0
  PieD9_Joint:
    has_velocity_limits: true
    max_velocity: 48
    has_acceleration_limits: false
    max_acceleration: 0
  PieI10_Joint:
    has_velocity_limits: true
    max_velocity: 48
    has_acceleration_limits: false
    max_acceleration: 0
  PieI12_Joint:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0