# Simulation settings for using moveit_sim_controllers
#moveit_sim_hw_interface:
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - CoxisD_Joint
    - MusloD3_Joint
    - MusloD5_Joint
    - PantorrillaD_Joint
    - PieD9_Joint
    - PieD11_Joint
    - CoxisI_Joint
    - MusloI4_Joint
    - MusloI6_Joint
    - PantorrillaI_Joint
    - PieI10_Joint
    - PieI12_Joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
